<?php

namespace Tests\Unit\Http\Livewire;

use App\Http\Livewire\CartComponent;
use PHPUnit\Framework\TestCase;

class CartComponentTest extends TestCase
{

    private $cart_component;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->cart_comonent = new CartComponent();
    }


    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test()
    {
        $this->assertTrue(true);
    }
}
